### ISSUE TITLE
try to use destroyed view - after applying pimp rules changes

### ISSUE THREAD

**Issue by kairos666** [kairos666/pmp-ui#41]
seen error stack trace in console

**Comment by kairos666** [comment]
EXCEPTION: Attempt to use a destroyed view: detectChanges
t.handleError @ error_handler.js:50
error_handler.js:55 ORIGINAL STACKTRACE:
t.handleError @ error_handler.js:55
error_handler.js:56 Error: Attempt to use a destroyed view: detectChanges
    at d (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:1441:1654)
    at e [as constructor] (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:142:359)
    at new e (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:989:661)
    at e.t.throwDestroyedError (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:43:6314)
    at e.t.detectChanges (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:43:5707)
    at e.t.internalDetectChanges (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:43:5542)
    at e.detectChangesInternal (http://localhost:4200/main.461834068585a13ba2da.bundle.js:19:5649)
    at e.t.detectChanges (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:43:5749)
    at t.detectChanges (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:1010:1536)
    at http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:521:5620
    at Array.forEach (native)
    at e.tick (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:521:5587)
    at http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:521:4167
    at t.invoke (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:1441:6949)
    at Object.onInvoke (http://localhost:4200/vendor.948d7caf57524323a92d.bundle.js:106:2659)
t.handleError @ error_handler.js:56
zone.js:407 e
